/* Automatically generated by p4c-ebpf from tests/samples/p4testdata/action-const-default.p4 on Fri Mar 19 10:42:14 2021
 */
#include "ebpf_kernel.h"

#include <stdbool.h>
#include <linux/if_ether.h>
#include "psa.h"


#define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
#define BYTES(w) ((w) / 8)
#define write_partial(a, w, s, v) do { *((u8*)a) = ((*((u8*)a)) & ~(EBPF_MASK(u8, w) << s)) | (v << s) ; } while (0)
#define write_byte(base, offset, v) do { *(u8*)((base) + (offset)) = (v); } while (0)

#define CLONE_MAX_PORTS 64
#define CLONE_MAX_INSTANCES 1
#define CLONE_MAX_CLONES (CLONE_MAX_PORTS * CLONE_MAX_INSTANCES)
#define CLONE_MAX_SESSIONS 1024

#ifndef PSA_PORT_RECIRCULATE
#error "PSA_PORT_RECIRCULATE not specified, please use -DPSA_PORT_RECIRCULATE=n option to specify index of recirculation interface (see the result of command 'ip link')"
#endif
#define P4C_PSA_PORT_RECIRCULATE 0xfffffffa

#define bpf_trace_message(fmt, ...)                                \
    do {                                                           \
        char ____fmt[] = fmt;                                      \
        bpf_trace_printk(____fmt, sizeof(____fmt), ##__VA_ARGS__); \
    } while(0)

struct internal_metadata {
    __u16 pkt_ether_type;
} __attribute__((aligned(4)));

struct list_key_t {
    __u32 port;
    __u16 instance;
};
typedef struct list_key_t elem_t;

struct element {
    struct clone_session_entry entry;
    elem_t next_id;
} __attribute__((aligned(4)));

struct ethernet_t {
    u64 dstAddr; /* EthernetAddress */
    u64 srcAddr; /* EthernetAddress */
    u16 etherType; /* bit<16> */
    u8 ebpf_valid;
};
struct ipv4_t {
    u8 version; /* bit<4> */
    u8 ihl; /* bit<4> */
    u8 diffserv; /* bit<8> */
    u16 totalLen; /* bit<16> */
    u16 identification; /* bit<16> */
    u8 flags; /* bit<3> */
    u16 fragOffset; /* bit<13> */
    u8 ttl; /* bit<8> */
    u8 protocol; /* bit<8> */
    u16 hdrChecksum; /* bit<16> */
    u32 srcAddr; /* bit<32> */
    u32 dstAddr; /* bit<32> */
    u8 ebpf_valid;
};
struct fwd_metadata_t {
};
struct empty_t {
};
struct metadata {
    struct fwd_metadata_t fwd_metadata; /* fwd_metadata_t */
};
struct headers {
    struct ethernet_t ethernet; /* ethernet_t */
    struct ipv4_t ipv4; /* ipv4_t */
};

struct ingress_tbl_const_action_key {
    u32 field0; /* istd.ingress_port */
} __attribute__((aligned(4)));
#define ACT_INGRESS_DO_FORWARD 1
struct ingress_tbl_const_action_value {
    unsigned int action;
    union {
        struct {
            u32 egress_port;
        } ingress_do_forward;
        struct {
        } _NoAction;
    } u;
};
REGISTER_START()
REGISTER_TABLE_INNER(clone_session_tbl_inner, BPF_MAP_TYPE_HASH, sizeof(elem_t), sizeof(struct element), 64, 1, 1)
REGISTER_TABLE_OUTER(clone_session_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, sizeof(__u32), sizeof(__u32), 1024, 1, clone_session_tbl_inner)
REGISTER_TABLE_INNER(multicast_grp_tbl_inner, BPF_MAP_TYPE_HASH, sizeof(elem_t), sizeof(struct element), 64, 2, 2)
REGISTER_TABLE_OUTER(multicast_grp_tbl, BPF_MAP_TYPE_ARRAY_OF_MAPS, sizeof(__u32), sizeof(__u32), 1024, 2, multicast_grp_tbl_inner)
REGISTER_TABLE(ingress_tbl_const_action, BPF_MAP_TYPE_HASH, sizeof(struct ingress_tbl_const_action_key), sizeof(struct ingress_tbl_const_action_value), 100)
REGISTER_TABLE(ingress_tbl_const_action_defaultAction, BPF_MAP_TYPE_ARRAY, sizeof(u32), sizeof(struct ingress_tbl_const_action_value), 1)
REGISTER_END()

SEC("map-initializer")
int map_initialize() {
    u32 ebpf_zero = 0;
    struct ingress_tbl_const_action_value val = {};
    val.action = ACT_INGRESS_DO_FORWARD;
    val.u.ingress_do_forward.egress_port = 5;

    int ret = BPF_MAP_UPDATE_ELEM(ingress_tbl_const_action_defaultAction, &ebpf_zero, &val, 0);
}

SEC("xdp/xdp-ingress")
int xdp_func(struct xdp_md *skb) {
    void *data = (void *)(long)skb->data;
    void *data_end = (void *)(long)skb->data_end;

    struct internal_metadata *meta;
    int ret = bpf_xdp_adjust_meta(skb, -(int)sizeof(*meta));
    if (ret < 0) {
        bpf_printk("[XDP] Error while adjusting meta %d", ret);
        return XDP_ABORTED;
    }
    meta = (struct internal_metadata *)(unsigned long)skb->data_meta;
    data = (void *)(long)skb->data;
    data_end = (void *)(long)skb->data_end;
    if ((void *) ((struct internal_metadata *) meta + 1) > data)
        return XDP_ABORTED;

    struct ethhdr *eth = data;
    if ((void *)((struct ethhdr *) eth + 1) > data_end) {
        return TC_ACT_SHOT;
    }
    meta->pkt_ether_type = eth->h_proto;
    eth->h_proto = bpf_htons(0x0800);

    return XDP_PASS;
}
inline u16 csum16_add(u16 csum, u16 addend) {
    u16 res = csum;
    res += addend;
    return (res + (res < addend));
}
inline u16 csum16_sub(u16 csum, u16 addend) {
    return csum16_add(csum, ~addend);
}
inline u16 csum_replace2(u16 csum, u16 old, u16 new) {
    return (~csum16_add(csum16_sub(~csum, old), new));
}
static __always_inline
int do_for_each(SK_BUFF *skb, void *map, unsigned int max_iter, void (*a)(SK_BUFF *, void *))
{
    elem_t head_idx = {0, 0};
    struct element *elem = bpf_map_lookup_elem(map, &head_idx);
    if (!elem) {
        return -1;
    }
    if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
        bpf_trace_message("do_for_each: No elements found in list\n");
        return 0;
    }
    elem_t next_id = elem->next_id;
    for (unsigned int i = 0; i < max_iter; i++) {
        struct element *elem = bpf_map_lookup_elem(map, &next_id);
        if (!elem) {
            break;
        }
        a(skb, &elem->entry);
        if (elem->next_id.port == 0 && elem->next_id.instance == 0) {
            break;
        }
        next_id = elem->next_id;
    }
    return 0;
}

static __always_inline
void do_clone(SK_BUFF *skb, void *data)
{
    struct clone_session_entry *entry = (struct clone_session_entry *) data;
    bpf_trace_message("do_clone: cloning pkt, egress_port=%d, cos=%d\n", entry->egress_port, entry->class_of_service);
    bpf_clone_redirect(skb, entry->egress_port, 0);
}

static __always_inline
int do_packet_clones(SK_BUFF * skb, void * map, __u32 session_id, PSA_PacketPath_t new_pkt_path, __u8 caller_id)
{
    bpf_trace_message("Clone#%d: pkt clone requested, session=%d\n", caller_id, session_id);
    struct psa_global_metadata * meta = (struct psa_global_metadata *) skb->cb;
    void * inner_map;
    inner_map = bpf_map_lookup_elem(map, &session_id);
    if (inner_map != NULL) {
        PSA_PacketPath_t original_pkt_path = meta->packet_path;
        meta->packet_path = new_pkt_path;
        if (do_for_each(skb, inner_map, CLONE_MAX_CLONES, &do_clone) < 0) {
            bpf_trace_message("Clone#%d: failed to clone packet", caller_id);
            return -1;
        }
        meta->packet_path = original_pkt_path;
    } else {
        bpf_trace_message("Clone#%d: session_id not found, no clones created\n", caller_id);
    }
    bpf_trace_message("Clone#%d: packet cloning finished\n", caller_id);
    return 0;
}

static __always_inline int process(SK_BUFF *skb, struct psa_ingress_output_metadata_t *ostd, struct empty_t *resubmit_meta)
{
    struct psa_global_metadata *meta = (struct psa_global_metadata *) skb->cb;
    if (meta->packet_path == NORMAL) {
        struct internal_metadata *md = (struct internal_metadata *)(unsigned long)skb->data_meta;
        if ((void *) ((struct internal_metadata *) md + 1) > (void *)(long)skb->data) {
            return TC_ACT_SHOT;
        }
        __u16 *ether_type = (__u16 *) ((void *) (long)skb->data + 12);
        if ((void *) ((__u16 *) ether_type + 1) >     (void *) (long) skb->data_end) {
            return TC_ACT_SHOT;
        }
        *ether_type = md->pkt_ether_type;
    }
    struct headers parsed_hdr = {
            .ethernet = {
                    .ebpf_valid = 0
            },
            .ipv4 = {
                    .ebpf_valid = 0
            },
    };
    struct metadata user_meta = {
            .fwd_metadata = {
            },
    };
    unsigned ebpf_packetOffsetInBits = 0;unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    unsigned char ebpf_byte;
    bpf_trace_message("classifier/tc-ingress parser: parsing new packet, path=%d\n", meta->packet_path);
    start: {
    bpf_trace_message("Parser: state start\n");
/* extract(parsed_hdr.ethernet)*/
    bpf_trace_message("Parser: check pkt_len=%%d < last_read_byte=%%d\n", ebpf_packetEnd - pkt, BYTES(ebpf_packetOffsetInBits + 112));
    if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
        bpf_trace_message("Parser: invalid packet (packet too short)\n");
        ebpf_errorCode = PacketTooShort;
        goto reject;
    }
    bpf_trace_message("Parser: extracting header parsed_hdr.ethernet\n");

    bpf_trace_message("Parser: extracting field dstAddr\n");
    parsed_hdr.ethernet.dstAddr = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
    ebpf_packetOffsetInBits += 48;
    bpf_trace_message("Parser: extracted dstAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.dstAddr);

    bpf_trace_message("Parser: extracting field srcAddr\n");
    parsed_hdr.ethernet.srcAddr = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
    ebpf_packetOffsetInBits += 48;
    bpf_trace_message("Parser: extracted srcAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.srcAddr);

    bpf_trace_message("Parser: extracting field etherType\n");
    parsed_hdr.ethernet.etherType = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted etherType=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ethernet.etherType);

    parsed_hdr.ethernet.ebpf_valid = 1;
    bpf_trace_message("Parser: extracted parsed_hdr.ethernet\n");

    switch (parsed_hdr.ethernet.etherType) {
        case 2048: goto parse_ipv4;
        default: goto accept;
    }
}
    parse_ipv4: {
    bpf_trace_message("Parser: state parse_ipv4\n");
/* extract(parsed_hdr.ipv4)*/
    bpf_trace_message("Parser: check pkt_len=%%d < last_read_byte=%%d\n", ebpf_packetEnd - pkt, BYTES(ebpf_packetOffsetInBits + 160));
    if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
        bpf_trace_message("Parser: invalid packet (packet too short)\n");
        ebpf_errorCode = PacketTooShort;
        goto reject;
    }
    bpf_trace_message("Parser: extracting header parsed_hdr.ipv4\n");

    bpf_trace_message("Parser: extracting field version\n");
    parsed_hdr.ipv4.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
    ebpf_packetOffsetInBits += 4;
    bpf_trace_message("Parser: extracted version=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.version);

    bpf_trace_message("Parser: extracting field ihl\n");
    parsed_hdr.ipv4.ihl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 4));
    ebpf_packetOffsetInBits += 4;
    bpf_trace_message("Parser: extracted ihl=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.ihl);

    bpf_trace_message("Parser: extracting field diffserv\n");
    parsed_hdr.ipv4.diffserv = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted diffserv=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.diffserv);

    bpf_trace_message("Parser: extracting field totalLen\n");
    parsed_hdr.ipv4.totalLen = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted totalLen=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.totalLen);

    bpf_trace_message("Parser: extracting field identification\n");
    parsed_hdr.ipv4.identification = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted identification=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.identification);

    bpf_trace_message("Parser: extracting field flags\n");
    parsed_hdr.ipv4.flags = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 5) & EBPF_MASK(u8, 3));
    ebpf_packetOffsetInBits += 3;
    bpf_trace_message("Parser: extracted flags=0x%llx (3 bits)\n", (unsigned long long) parsed_hdr.ipv4.flags);

    bpf_trace_message("Parser: extracting field fragOffset\n");
    parsed_hdr.ipv4.fragOffset = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u16, 13));
    ebpf_packetOffsetInBits += 13;
    bpf_trace_message("Parser: extracted fragOffset=0x%llx (13 bits)\n", (unsigned long long) parsed_hdr.ipv4.fragOffset);

    bpf_trace_message("Parser: extracting field ttl\n");
    parsed_hdr.ipv4.ttl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted ttl=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.ttl);

    bpf_trace_message("Parser: extracting field protocol\n");
    parsed_hdr.ipv4.protocol = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted protocol=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.protocol);

    bpf_trace_message("Parser: extracting field hdrChecksum\n");
    parsed_hdr.ipv4.hdrChecksum = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted hdrChecksum=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.hdrChecksum);

    bpf_trace_message("Parser: extracting field srcAddr\n");
    parsed_hdr.ipv4.srcAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 32;
    bpf_trace_message("Parser: extracted srcAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.srcAddr);

    bpf_trace_message("Parser: extracting field dstAddr\n");
    parsed_hdr.ipv4.dstAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 32;
    bpf_trace_message("Parser: extracted dstAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.dstAddr);

    parsed_hdr.ipv4.ebpf_valid = 1;
    bpf_trace_message("Parser: extracted parsed_hdr.ipv4\n");

    goto accept;
}

    reject: {
    bpf_trace_message("Packet rejected\n");
    return TC_ACT_SHOT;
}

    accept:
    {
        struct psa_ingress_input_metadata_t istd = {
                .ingress_port = skb->ifindex,
                .packet_path = meta->packet_path,
                .ingress_timestamp = skb->tstamp,
                .parser_error = ebpf_errorCode,
        };
        bpf_trace_message("classifier/tc-ingress control: packet processing started\n");
        u8 hit_1;
        struct psa_ingress_output_metadata_t *meta_1;
        {
            bpf_trace_message("Control: applying tbl_const_action_0\n");
            {
                /* construct key */
                struct ingress_tbl_const_action_key key = {};
                key.field0 = istd.ingress_port;
                bpf_trace_message("Control: key istd.ingress_port=0x%llx\n", (unsigned long long) key.field0);
                /* value */
                struct ingress_tbl_const_action_value *value = NULL;
                /* perform lookup */
                bpf_trace_message("Control: performing table lookup\n");
                value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_const_action, &key);
                if (value == NULL) {
                    /* miss; find default action */
                    bpf_trace_message("Control: Entry not found, going to default action\n");
                    hit_1 = 0;
                    value = BPF_MAP_LOOKUP_ELEM(ingress_tbl_const_action_defaultAction, &ebpf_zero);
                } else {
                    hit_1 = 1;
                }
                if (value != NULL) {
                    /* run action */
                    switch (value->action) {
                        case ACT_INGRESS_DO_FORWARD:
                            bpf_trace_message("Control: executing action ingress_do_forward\n");
                            bpf_trace_message("Control: param egress_port=0x%llx (32 bits)\n", (unsigned long long) (value->u.ingress_do_forward.egress_port));
                            {
                                {
                                    meta_1 = ostd;
                                    meta_1->drop = false;
                                    meta_1->multicast_group = 0;
                                    meta_1->egress_port = value->u.ingress_do_forward.egress_port;
                                    ostd = meta_1;
                                }
                            }
                            break;
                        case 0:
                            bpf_trace_message("Control: executing action _NoAction\n");
                            {
                            }
                            break;
                        default:
                            bpf_trace_message("Control: Invalid action type, aborting\n");
                            return TC_ACT_SHOT;
                    }
                } else {
                    bpf_trace_message("Control: Entry not found, aborting\n");
                    return TC_ACT_SHOT;
                }
            }
            bpf_trace_message("Control: tbl_const_action_0 applied\n");
            ;
        }
    }
    bpf_trace_message("classifier/tc-ingress control: packet processing finished\n");
    {
        {
            ;
            ;
        }

        if (ostd->clone) {
            do_packet_clones(skb, &clone_session_tbl, ostd->clone_session_id, CLONE_I2E, 1);
        }
        if (ostd->drop) {
            bpf_trace_message("PreDeparser: dropping packet..\n");
            return TC_ACT_SHOT;
        }
        if (ostd->resubmit) {
            bpf_trace_message("PreDeparser: resubmitting packet, skipping deparser..\n");
            meta->packet_path = RESUBMIT;
            return TC_ACT_UNSPEC;
        }
        int outHeaderLength = 0;
        if (parsed_hdr.ethernet.ebpf_valid) {
            outHeaderLength += 112;
        }
        if (parsed_hdr.ipv4.ebpf_valid) {
            outHeaderLength += 160;
        }

        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        bpf_trace_message("Deparser: pkt_len adjusting by %d B\n", outHeaderOffset);
        int returnCode = 0;
        returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
        if (returnCode) {
            bpf_trace_message("Deparser: pkt_len adjust failed\n");
            return TC_ACT_SHOT;
        }
        bpf_trace_message("Deparser: pkt_len adjusted\n");
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;
        if (parsed_hdr.ethernet.ebpf_valid) {
            bpf_trace_message("Deparser: emitting header parsed_hdr.ethernet\n");
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
                bpf_trace_message("Deparser: invalid packet (packet too short)\n");
                return TC_ACT_SHOT;
            }

            bpf_trace_message("Deparser: emitting field dstAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.dstAddr);
            parsed_hdr.ethernet.dstAddr = htonll(parsed_hdr.ethernet.dstAddr << 16);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;
            bpf_trace_message("Deparser: emitted dstAddr\n");

            bpf_trace_message("Deparser: emitting field srcAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.srcAddr);
            parsed_hdr.ethernet.srcAddr = htonll(parsed_hdr.ethernet.srcAddr << 16);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;
            bpf_trace_message("Deparser: emitted srcAddr\n");

            bpf_trace_message("Deparser: emitting field etherType=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ethernet.etherType);
            parsed_hdr.ethernet.etherType = bpf_htons(parsed_hdr.ethernet.etherType);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.etherType))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.etherType))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted etherType\n");

            bpf_trace_message("Deparser: emitted parsed_hdr.ethernet\n");
        }
        if (parsed_hdr.ipv4.ebpf_valid) {
            bpf_trace_message("Deparser: emitting header parsed_hdr.ipv4\n");
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
                bpf_trace_message("Deparser: invalid packet (packet too short)\n");
                return TC_ACT_SHOT;
            }

            bpf_trace_message("Deparser: emitting field version=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.version);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;
            bpf_trace_message("Deparser: emitted version\n");

            bpf_trace_message("Deparser: emitting field ihl=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.ihl);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.ihl))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;
            bpf_trace_message("Deparser: emitted ihl\n");

            bpf_trace_message("Deparser: emitting field diffserv=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.diffserv);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.diffserv))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted diffserv\n");

            bpf_trace_message("Deparser: emitting field totalLen=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.totalLen);
            parsed_hdr.ipv4.totalLen = bpf_htons(parsed_hdr.ipv4.totalLen);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.totalLen))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.totalLen))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted totalLen\n");

            bpf_trace_message("Deparser: emitting field identification=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.identification);
            parsed_hdr.ipv4.identification = bpf_htons(parsed_hdr.ipv4.identification);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.identification))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.identification))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted identification\n");

            bpf_trace_message("Deparser: emitting field flags=0x%llx (3 bits)\n", (unsigned long long) parsed_hdr.ipv4.flags);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.flags))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 3, 5, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 3;
            bpf_trace_message("Deparser: emitted flags\n");

            bpf_trace_message("Deparser: emitting field fragOffset=0x%llx (13 bits)\n", (unsigned long long) parsed_hdr.ipv4.fragOffset);
            parsed_hdr.ipv4.fragOffset = bpf_htons(parsed_hdr.ipv4.fragOffset << 3);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.fragOffset))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 5, 0, (ebpf_byte >> 3));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 3, 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.fragOffset))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 5, 0, (ebpf_byte >> 3));
            ebpf_packetOffsetInBits += 13;
            bpf_trace_message("Deparser: emitted fragOffset\n");

            bpf_trace_message("Deparser: emitting field ttl=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.ttl);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.ttl))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted ttl\n");

            bpf_trace_message("Deparser: emitting field protocol=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.protocol);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.protocol))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted protocol\n");

            bpf_trace_message("Deparser: emitting field hdrChecksum=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.hdrChecksum);
            parsed_hdr.ipv4.hdrChecksum = bpf_htons(parsed_hdr.ipv4.hdrChecksum);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.hdrChecksum))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.hdrChecksum))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted hdrChecksum\n");

            bpf_trace_message("Deparser: emitting field srcAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.srcAddr);
            parsed_hdr.ipv4.srcAddr = htonl(parsed_hdr.ipv4.srcAddr);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;
            bpf_trace_message("Deparser: emitted srcAddr\n");

            bpf_trace_message("Deparser: emitting field dstAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.dstAddr);
            parsed_hdr.ipv4.dstAddr = htonl(parsed_hdr.ipv4.dstAddr);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;
            bpf_trace_message("Deparser: emitted dstAddr\n");

            bpf_trace_message("Deparser: emitted parsed_hdr.ipv4\n");
        }

    }
    return TC_ACT_UNSPEC;
}
SEC("classifier/tc-ingress")
int tc_ingress_func(SK_BUFF *skb) {
    struct psa_ingress_output_metadata_t ostd = {
            .drop = true,
    };

    struct empty_t resubmit_meta;
    int i = 0;
    int ret = TC_ACT_UNSPEC;
#pragma clang loop unroll(disable)
    for (i = 0; i < 4; i++) {
        ostd.resubmit = 0;
        ret = process(skb, &ostd, &resubmit_meta);
        if (ostd.drop == 1 || ostd.resubmit == 0) {
            break;
        }
    }
    if (ret != TC_ACT_UNSPEC) {
        return ret;
    }
    if (ostd.multicast_group != 0) {
        bpf_trace_message("IngressTM: Performing multicast, multicast_group=%u\n", ostd.multicast_group);
        do_packet_clones(skb, &multicast_grp_tbl, ostd.multicast_group, NORMAL_MULTICAST, 2);
        bpf_trace_message("IngressTM: Multicast done, dropping source packet\n");
        return TC_ACT_SHOT;
    }
    bpf_trace_message("IngressTM: Sending packet out of port %d\n", ostd.egress_port);
    return bpf_redirect(ostd.egress_port, 0);
}
SEC("classifier/tc-egress")
int tc_egress_func(SK_BUFF *skb) {
    struct psa_global_metadata *meta = (struct psa_global_metadata *) skb->cb;
    struct headers parsed_hdr = {
            .ethernet = {
                    .ebpf_valid = 0
            },
            .ipv4 = {
                    .ebpf_valid = 0
            },
    };
    unsigned ebpf_packetOffsetInBits = 0;unsigned ebpf_packetOffsetInBits_save = 0;
    ParserError_t ebpf_errorCode = NoError;
    void* pkt = ((void*)(long)skb->data);
    void* ebpf_packetEnd = ((void*)(long)skb->data_end);
    u32 ebpf_zero = 0;
    unsigned char ebpf_byte;
    struct psa_egress_input_metadata_t istd = {
            .class_of_service = meta->class_of_service,
            .egress_port = skb->ifindex,
            .packet_path = meta->packet_path,
            .instance = meta->instance,
            .egress_timestamp = skb->tstamp,
            .parser_error = ebpf_errorCode,
    };
    if (istd.egress_port == PSA_PORT_RECIRCULATE) {
        istd.egress_port = P4C_PSA_PORT_RECIRCULATE;
    }
    struct psa_egress_output_metadata_t ostd = {
            .clone = false,
            .drop = false,
    };

    bpf_trace_message("classifier/tc-egress parser: parsing new packet, path=%d\n", istd.packet_path);
    start: {
    bpf_trace_message("Parser: state start\n");
/* extract(parsed_hdr.ethernet)*/
    bpf_trace_message("Parser: check pkt_len=%%d < last_read_byte=%%d\n", ebpf_packetEnd - pkt, BYTES(ebpf_packetOffsetInBits + 112));
    if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
        bpf_trace_message("Parser: invalid packet (packet too short)\n");
        ebpf_errorCode = PacketTooShort;
        goto reject;
    }
    bpf_trace_message("Parser: extracting header parsed_hdr.ethernet\n");

    bpf_trace_message("Parser: extracting field dstAddr\n");
    parsed_hdr.ethernet.dstAddr = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
    ebpf_packetOffsetInBits += 48;
    bpf_trace_message("Parser: extracted dstAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.dstAddr);

    bpf_trace_message("Parser: extracting field srcAddr\n");
    parsed_hdr.ethernet.srcAddr = (u64)((load_dword(pkt, BYTES(ebpf_packetOffsetInBits)) >> 16) & EBPF_MASK(u64, 48));
    ebpf_packetOffsetInBits += 48;
    bpf_trace_message("Parser: extracted srcAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.srcAddr);

    bpf_trace_message("Parser: extracting field etherType\n");
    parsed_hdr.ethernet.etherType = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted etherType=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ethernet.etherType);

    parsed_hdr.ethernet.ebpf_valid = 1;
    bpf_trace_message("Parser: extracted parsed_hdr.ethernet\n");

    switch (parsed_hdr.ethernet.etherType) {
        case 2048: goto parse_ipv4;
        default: goto accept;
    }
}
    parse_ipv4: {
    bpf_trace_message("Parser: state parse_ipv4\n");
/* extract(parsed_hdr.ipv4)*/
    bpf_trace_message("Parser: check pkt_len=%%d < last_read_byte=%%d\n", ebpf_packetEnd - pkt, BYTES(ebpf_packetOffsetInBits + 160));
    if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
        bpf_trace_message("Parser: invalid packet (packet too short)\n");
        ebpf_errorCode = PacketTooShort;
        goto reject;
    }
    bpf_trace_message("Parser: extracting header parsed_hdr.ipv4\n");

    bpf_trace_message("Parser: extracting field version\n");
    parsed_hdr.ipv4.version = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 4) & EBPF_MASK(u8, 4));
    ebpf_packetOffsetInBits += 4;
    bpf_trace_message("Parser: extracted version=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.version);

    bpf_trace_message("Parser: extracting field ihl\n");
    parsed_hdr.ipv4.ihl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u8, 4));
    ebpf_packetOffsetInBits += 4;
    bpf_trace_message("Parser: extracted ihl=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.ihl);

    bpf_trace_message("Parser: extracting field diffserv\n");
    parsed_hdr.ipv4.diffserv = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted diffserv=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.diffserv);

    bpf_trace_message("Parser: extracting field totalLen\n");
    parsed_hdr.ipv4.totalLen = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted totalLen=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.totalLen);

    bpf_trace_message("Parser: extracting field identification\n");
    parsed_hdr.ipv4.identification = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted identification=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.identification);

    bpf_trace_message("Parser: extracting field flags\n");
    parsed_hdr.ipv4.flags = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits)) >> 5) & EBPF_MASK(u8, 3));
    ebpf_packetOffsetInBits += 3;
    bpf_trace_message("Parser: extracted flags=0x%llx (3 bits)\n", (unsigned long long) parsed_hdr.ipv4.flags);

    bpf_trace_message("Parser: extracting field fragOffset\n");
    parsed_hdr.ipv4.fragOffset = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))) & EBPF_MASK(u16, 13));
    ebpf_packetOffsetInBits += 13;
    bpf_trace_message("Parser: extracted fragOffset=0x%llx (13 bits)\n", (unsigned long long) parsed_hdr.ipv4.fragOffset);

    bpf_trace_message("Parser: extracting field ttl\n");
    parsed_hdr.ipv4.ttl = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted ttl=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.ttl);

    bpf_trace_message("Parser: extracting field protocol\n");
    parsed_hdr.ipv4.protocol = (u8)((load_byte(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 8;
    bpf_trace_message("Parser: extracted protocol=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.protocol);

    bpf_trace_message("Parser: extracting field hdrChecksum\n");
    parsed_hdr.ipv4.hdrChecksum = (u16)((load_half(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 16;
    bpf_trace_message("Parser: extracted hdrChecksum=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.hdrChecksum);

    bpf_trace_message("Parser: extracting field srcAddr\n");
    parsed_hdr.ipv4.srcAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 32;
    bpf_trace_message("Parser: extracted srcAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.srcAddr);

    bpf_trace_message("Parser: extracting field dstAddr\n");
    parsed_hdr.ipv4.dstAddr = (u32)((load_word(pkt, BYTES(ebpf_packetOffsetInBits))));
    ebpf_packetOffsetInBits += 32;
    bpf_trace_message("Parser: extracted dstAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.dstAddr);

    parsed_hdr.ipv4.ebpf_valid = 1;
    bpf_trace_message("Parser: extracted parsed_hdr.ipv4\n");

    goto accept;
}

    reject: {
    bpf_trace_message("Packet rejected\n");
    return TC_ACT_SHOT;
}

    accept:
    {
        bpf_trace_message("classifier/tc-egress control: packet processing started\n");
        u8 hit_2;
        {
        }
    }
    bpf_trace_message("classifier/tc-egress control: packet processing finished\n");
    {
        bpf_trace_message("classifier/tc-egress deparser: packet deparsing started\n");
        {
            ;
            ;
        }
        int outHeaderLength = 0;
        if (parsed_hdr.ethernet.ebpf_valid) {
            outHeaderLength += 112;
        }
        if (parsed_hdr.ipv4.ebpf_valid) {
            outHeaderLength += 160;
        }

        int outHeaderOffset = BYTES(outHeaderLength) - BYTES(ebpf_packetOffsetInBits);
        bpf_trace_message("Deparser: pkt_len adjusting by %d B\n", outHeaderOffset);
        int returnCode = 0;
        returnCode = bpf_skb_adjust_room(skb, outHeaderOffset, 1, 0);
        if (returnCode) {
            bpf_trace_message("Deparser: pkt_len adjust failed\n");
            return TC_ACT_SHOT;
        }
        bpf_trace_message("Deparser: pkt_len adjusted\n");
        pkt = ((void*)(long)skb->data);
        ebpf_packetEnd = ((void*)(long)skb->data_end);
        ebpf_packetOffsetInBits = 0;
        if (parsed_hdr.ethernet.ebpf_valid) {
            bpf_trace_message("Deparser: emitting header parsed_hdr.ethernet\n");
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 112)) {
                bpf_trace_message("Deparser: invalid packet (packet too short)\n");
                return TC_ACT_SHOT;
            }

            bpf_trace_message("Deparser: emitting field dstAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.dstAddr);
            parsed_hdr.ethernet.dstAddr = htonll(parsed_hdr.ethernet.dstAddr << 16);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.dstAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;
            bpf_trace_message("Deparser: emitted dstAddr\n");

            bpf_trace_message("Deparser: emitting field srcAddr=0x%llx (48 bits)\n", (unsigned long long) parsed_hdr.ethernet.srcAddr);
            parsed_hdr.ethernet.srcAddr = htonll(parsed_hdr.ethernet.srcAddr << 16);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[4];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 4, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.srcAddr))[5];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 5, (ebpf_byte));
            ebpf_packetOffsetInBits += 48;
            bpf_trace_message("Deparser: emitted srcAddr\n");

            bpf_trace_message("Deparser: emitting field etherType=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ethernet.etherType);
            parsed_hdr.ethernet.etherType = bpf_htons(parsed_hdr.ethernet.etherType);
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.etherType))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ethernet.etherType))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted etherType\n");

            bpf_trace_message("Deparser: emitted parsed_hdr.ethernet\n");
        }
        if (parsed_hdr.ipv4.ebpf_valid) {
            bpf_trace_message("Deparser: emitting header parsed_hdr.ipv4\n");
            if (ebpf_packetEnd < pkt + BYTES(ebpf_packetOffsetInBits + 160)) {
                bpf_trace_message("Deparser: invalid packet (packet too short)\n");
                return TC_ACT_SHOT;
            }

            bpf_trace_message("Deparser: emitting field version=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.version);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.version))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 4, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;
            bpf_trace_message("Deparser: emitted version\n");

            bpf_trace_message("Deparser: emitting field ihl=0x%llx (4 bits)\n", (unsigned long long) parsed_hdr.ipv4.ihl);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.ihl))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 4, 0, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 4;
            bpf_trace_message("Deparser: emitted ihl\n");

            bpf_trace_message("Deparser: emitting field diffserv=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.diffserv);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.diffserv))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted diffserv\n");

            bpf_trace_message("Deparser: emitting field totalLen=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.totalLen);
            parsed_hdr.ipv4.totalLen = bpf_htons(parsed_hdr.ipv4.totalLen);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.totalLen))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.totalLen))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted totalLen\n");

            bpf_trace_message("Deparser: emitting field identification=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.identification);
            parsed_hdr.ipv4.identification = bpf_htons(parsed_hdr.ipv4.identification);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.identification))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.identification))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted identification\n");

            bpf_trace_message("Deparser: emitting field flags=0x%llx (3 bits)\n", (unsigned long long) parsed_hdr.ipv4.flags);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.flags))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 3, 5, (ebpf_byte >> 0));
            ebpf_packetOffsetInBits += 3;
            bpf_trace_message("Deparser: emitted flags\n");

            bpf_trace_message("Deparser: emitting field fragOffset=0x%llx (13 bits)\n", (unsigned long long) parsed_hdr.ipv4.fragOffset);
            parsed_hdr.ipv4.fragOffset = bpf_htons(parsed_hdr.ipv4.fragOffset << 3);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.fragOffset))[0];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0, 5, 0, (ebpf_byte >> 3));
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 0 + 1, 3, 5, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.fragOffset))[1];
            write_partial(pkt + BYTES(ebpf_packetOffsetInBits) + 1, 5, 0, (ebpf_byte >> 3));
            ebpf_packetOffsetInBits += 13;
            bpf_trace_message("Deparser: emitted fragOffset\n");

            bpf_trace_message("Deparser: emitting field ttl=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.ttl);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.ttl))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted ttl\n");

            bpf_trace_message("Deparser: emitting field protocol=0x%llx (8 bits)\n", (unsigned long long) parsed_hdr.ipv4.protocol);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.protocol))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_packetOffsetInBits += 8;
            bpf_trace_message("Deparser: emitted protocol\n");

            bpf_trace_message("Deparser: emitting field hdrChecksum=0x%llx (16 bits)\n", (unsigned long long) parsed_hdr.ipv4.hdrChecksum);
            parsed_hdr.ipv4.hdrChecksum = bpf_htons(parsed_hdr.ipv4.hdrChecksum);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.hdrChecksum))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.hdrChecksum))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_packetOffsetInBits += 16;
            bpf_trace_message("Deparser: emitted hdrChecksum\n");

            bpf_trace_message("Deparser: emitting field srcAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.srcAddr);
            parsed_hdr.ipv4.srcAddr = htonl(parsed_hdr.ipv4.srcAddr);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.srcAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;
            bpf_trace_message("Deparser: emitted srcAddr\n");

            bpf_trace_message("Deparser: emitting field dstAddr=0x%llx (32 bits)\n", (unsigned long long) parsed_hdr.ipv4.dstAddr);
            parsed_hdr.ipv4.dstAddr = htonl(parsed_hdr.ipv4.dstAddr);
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[0];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 0, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[1];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 1, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[2];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 2, (ebpf_byte));
            ebpf_byte = ((char*)(&parsed_hdr.ipv4.dstAddr))[3];
            write_byte(pkt, BYTES(ebpf_packetOffsetInBits) + 3, (ebpf_byte));
            ebpf_packetOffsetInBits += 32;
            bpf_trace_message("Deparser: emitted dstAddr\n");

            bpf_trace_message("Deparser: emitted parsed_hdr.ipv4\n");
        }

    }
    bpf_trace_message("classifier/tc-egress deparser: packet deparsing finished\n");
    if (ostd.clone) {
        do_packet_clones(skb, &clone_session_tbl, ostd.clone_session_id, CLONE_E2E, 3);
    }

    if (ostd.drop) {
        bpf_trace_message("EgressTM: Packet dropped due to metadata\n");
        return TC_ACT_SHOT;
    }

    if (istd.egress_port == P4C_PSA_PORT_RECIRCULATE) {
        bpf_trace_message("EgressTM: recirculating packet\n");
        meta->packet_path = RECIRCULATE;
        return bpf_redirect(PSA_PORT_RECIRCULATE, BPF_F_INGRESS);
    }

    bpf_trace_message("EgressTM: output packet to port %d\n", skb->ifindex);
    return TC_ACT_OK;
}
char _license[] SEC("license") = "GPL";
