name: "ptf-p4c"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ptf-linux:
    env:
      UNIFIED: ON
      ENABLE_GMP: ON
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build (Linux)
      run: |
        docker build --network host -t p4c-ptf -f Dockerfile.ptf --build-arg MAKEFLAGS=-j8 --build-arg IMAGE_TYPE=test --build-arg ENABLE_UNIFIED_COMPILATION=$UNIFIED --build-arg ENABLE_GMP=$ENABLE_GMP .

    - name: Run PTF tests (Linux)
      run: |
        sudo docker run --privileged -v /sys/fs/bpf:/sys/fs/bpf -w /p4c/build p4c-ptf bash -c 'make check-ebpf-psa-ptf; EXIT_CODE=$?; cat Testing/Temporary/LastTest.log; exit $EXIT_CODE'